url_app/urls.py
from django.urls import path
from . import views

app_name='url_app'
urlpatterns = [
    path('', views.index, name='index'),
    path('short/', views.short, name='short'),
    path('<str:short>/', views.url_redirect, name='redirect'),
]

url_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('url_app.urls'))
]

url_app/models.py
from django.db import models

# Create your models here.
class UrlItem(models.Model):
    long = models.TextField()
    # use code generator for short code (6 digit)
    short = models.TextField(blank=True, null=True)
    clicks = models.IntegerField(default = 0)
    

    def __str__(self):
        return self.long

class Click(models.Model):
    username = models.TextField(blank=True, null=True)
    computer_name = models.TextField(blank=True, null=True)
    os = models.TextField(blank=True, null=True)
    urlitem = models.ForeignKey(UrlItem, on_delete=models.CASCADE)

    def __str__(self):
        return self.urlitem

url_app/views.py
from django.http.request import HttpRequest
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponseRedirect
import random
import string
from django.db import models

from url_app.models import UrlItem, Click


# Create your views here.
def index(request):

    return render(request, 'url_app/index.html')

def short(request):
    link = UrlItem(long=request.POST['link'])

    code = ''
    x = string.ascii_letters + string.digits
    while len(code) < 6:
        code += random.choice(x)
    link.short = code
    link.save()
    
    context = {'link': link, 'code': code}
    return render(request, 'url_app/index.html', context)


def url_redirect(request, short):
    m = request.META   
    
    link = get_object_or_404(UrlItem, short=short)
    link.clicks += int(1)    

    new_data = Click()
    new_data.urlitem = link
    
    
    new_data.save()   
    link.save()
    
    return redirect(f'{link.long}')  

url_app/templates/url_app/index.html
{% load static %}
<!DOCTYPE>
<html>
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Fruktur&family=Josefin+Sans&family=Lobster&family=Noto+Serif+Display&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="{% static 'url_app/main.css' %}"/>
    <title>Shorty.</title>

    </head>
    <body>
        <div class='wrapper'>
            <h1>Welcome to Shorty.</h1>
            <p>Enter URL to generate</p>
            <p>personalized short code</p>
                <form action="{% url 'url_app:short' %} " method="post">
                    {% csrf_token %}
                    <div class='gen'>
                        <input type="text" name="link"/>
                        <br>
                        <button type= "submit"> Generate</button>
                    </div>
                </form>
                {% if code %}
                <p>Code: </p> <p>http://shorty-url-app.herokuapp.com/{{code}}</p>
                
                <h3><a href="{% url 'url_app:redirect' code %}">Let's Go.</a> </h3>

                {% endif %}
        </div>
    </body>
</html>